name: ginkgo-main_v2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # jangan pakai latest biar stabil

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Building Kernel
      env:
        TZ: Asia/Jakarta
        CHATID: -1002287610863
        BOT_TOKEN: 8759815397:AAH77oV6G6bO4TaxoOPvMd9kA2KYk0hGozE
      run: |
        chmod +x kernel.sh
        bash kernel.sh
